### ISSUE TITLE
Pull Request #12 (Merge chooseVenue_1) failed

### ISSUE THREAD

**Issue by NtandoRaji** [tarunaidoo/Infrastructure_Management#13]
Error: 
The content server has rejected the request with: BadRequest
Reason: This Static Web App already has the maximum number of staging environments (System.Threading.Tasks.Task`1[System.Int32]). Please remove one and try again.

Reason: 
This error occurs because the Azure Static Web App you're working with has reached the maximum number of allowed staging environments. Each Static Web App typically allows up to five staging environments.

Solution:
Remove one of the existing staging environments to make room for a new one.

Could someone please resolve this issue?

**Comment by Tania908** [comment]
https://www.justinjbird.me/blog/2023/static-web-app-already-has-maximum-number-of-staging-environments/

https://stackoverflow.com/questions/68844740/this-static-web-app-has-the-maximum-number-of-staging-environments

Here are some websites I've found but who ever is running the SWA probably will only have access to this. The member who has access to SWA follow these instructions and I think we should be good

**Comment by shaneelkassen** [comment]
Ive run into this issue before, I'll fix it.

**Comment by shaneelkassen** [comment]
Under the Envionments tab on the azure portal, sometimes a staging environment is created and not closed. This will cause that error, so you have to delete any old unclosed environments under environment previews.  I resolved this and I re-run the checks on your pull request and everything is working now.

**Comment by NtandoRaji** [comment]
Thank you
